#!/bin/bash

set -e

which spiff > /dev/null 2>&1 || {
  echo "Aborted. Please install spiff by following https://github.com/cloudfoundry-incubator/spiff#installation" 1>&2
  exit 1
}

templates="$(dirname $0)/templates"

infrastructure="${1:?}"

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "warden" ] ; then
  echo "Usage: ./scripts/generate_deployment_manifest <aws|warden> [stubs...]" 1>&2
  exit 1
fi

spiff merge \
  "$templates/k8s-deployment.yml" \
  "$templates/k8s-jobs.yml" \
  "$templates/k8s-infrastructure-${infrastructure}.yml" \
  "$@"
