compilation:
  cloud_properties: {}

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties: {}

networks:
  - name: default
    subnets:
      - range: 10.244.8.4/30
        reserved: [10.244.8.5]
        static: [10.244.8.6]
        cloud_properties: {}
      - range: 10.244.8.8/30
        reserved: [10.244.8.9]
        static: [10.244.8.10]
        cloud_properties: {}
      - range: 10.244.8.12/30
        reserved: [10.244.8.13]
        static: [10.244.8.14]
        cloud_properties: {}
      - range: 10.244.8.16/30
        reserved: [10.244.8.17]
        static: [10.244.8.18]
        cloud_properties: {}
      - range: 10.244.8.20/30
        reserved: [10.244.8.21]
        static: [10.244.8.22]
        cloud_properties: {}
      - range: 10.244.8.24/30
        reserved: [10.244.8.25]
        static: []
        cloud_properties: {}
      - range: 10.244.8.28/30
        reserved: [10.244.8.29]
        static: []
        cloud_properties: {}
      - range: 10.244.8.32/30
        reserved: [10.244.8.33]
        static: []
        cloud_properties: {}
      - range: 10.244.8.36/30
        reserved: [10.244.8.37]
        static: []
        cloud_properties: {}

jobs:
  - name: master
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(0) ))
  - name: minion
    instances: 2
    networks:
      - name: default
        static_ips: (( static_ips(1, 2) ))
  - name: guestbook-example
    lifecycle: errand
    instances: 1
    networks:
      - name: default

properties:
  <<: (( merge ))
  apiserver:
    host: (( jobs.master.networks.default.static_ips.[0] ))
    machines: (( jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
  etcd:
    machines: (( jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
