compilation:
  network: kubernetes-warden

stemcells:
    alias: warden-default
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

jobs:
- name: master
  instances: 1
  stemcell: warden-default
  networks:
  - name: kubernetes-warden
    static_ips: (( static_ips(0) ))
- name: minion
  instances: 2
  stemcell: warden-default
  networks:
  - name: kubernetes-warden
    static_ips: (( static_ips(1, 2) ))
- name: guestbook-example
  stemcell: warden-default
  lifecycle: errand
  instances: 1
  networks:
  - name: kubernetes-warden

properties:
  apiserver:
    host: (( grab jobs.master.networks.kubernetes-warden.static_ips.[0] ))
    hosts: (( grab jobs.master.networks.kubernetes-warden.static_ips ))
  etcd:
    machines: (( grab jobs.master.networks.kubernetes-warden.static_ips jobs.minion.networks.kubernetes-warden.static_ips ))

properties:
  apiserver:
    ip: (( param "specify apiserver host" ))
    hosts: (( param "specify apiserver hosts" ))
  etcd:
    machines: (( param "specify etcd machines" ))
    require_ssl: false
    peer_require_ssl: false
  certs: {}
  cloud-provider: ~
  cloud-credentials: {}
