compilation:
  vm_type: kubernetes_compilation
  network: kubernetes-aws

stemcells:
    alias: aws-default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
- name: consul
  instances: 3
  stemcell: aws-default
  vm_type: kubernetes_aws_default
  networks:
  - name: kubernetes-aws
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[0] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[1] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[2] ))

- name: etcd
  instances: 3
  stemcell: aws-default
  vm_type: kubernetes_etcd
  vm_extension: kubernetes-etcd-profile
  networks:
  - name: kubernetes-aws
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[3] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[4] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[5] ))

- name: master
  instances: 3
  stemcell: aws-default
  vm_type: kubernetes_master
  vm_extension: kubernetes-master-profile
  networks:
  - name: kubernetes-aws
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[6] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[7] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[8] ))

- name: minion
  instances: 2
  stemcell: aws-default
  vm_type: kubernetes_minion
  vm_extension: kubernetes-minion-profile
  networks:
  - name: kubernetes-aws
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[9] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[10] ))

- name: guestbook-example
  lifecycle: errand
  instances: 1
  stemcell: aws-default
  vm_type: kubernetes_errand
  networks:
  - name: kubernetes-aws

properties:
  nodes: (( grab jobs.master.networks.kubernetes-aws.static_ips jobs.minion.networks.kubernetes-aws.static_ips ))
  apiserver:
    ip: (( grab jobs.etcd.networks.kubernetes-aws.static_ips.[0] ))
    host: (( grab jobs.master.networks.kubernetes-aws.static_ips.[0] ))
    hosts: (( grab jobs.master.networks.kubernetes-aws.static_ips ))
  consul:
    join_host: (( grab jobs.consul.networks.kubernetes-aws.static_ips.[0] ))
    join_hosts: (( grab jobs.consul.networks.kubernetes-aws.static_ips ))
  etcd:
    machines: (( grab jobs.etcd.networks.kubernetes-aws.static_ips ))
