jobs:
- name: master
  <<: (( merge ))
  templates:
  - name: docker
  - name: etcd
  - name: flannel
  - name: kubernetes-minion
  - name: kubernetes-master
  instances: 3
  resource_pool: master
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( merge ))
  properties:
    networks:
      apps: default
- name: minion
  <<: (( merge ))
  templates:
  - name: docker
  - name: etcd
  - name: flannel
  - name: kubernetes-minion
  instances: 3
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( merge ))
  properties:
    networks:
      apps: default
- name: create-kubernetes-dns
  lifecycle: errand
  templates:
  - name: create-kubernetes-dns
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default
- name: guestbook-example
  lifecycle: errand
  templates:
  - name: guestbook-example
  - name: flannel
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default

properties:
  <<: (( merge ))
  apiserver: (( merge ))
  etcd:
    machines: (( merge ))
    require_ssl: false
    peer_require_ssl: false
  cloud-provider: (( merge || ~ ))
  cloud-credentials: (( merge || {} ))

resource_pools: (( merge ))
