#!/bin/bash
# vim: set ft=sh

set -e -x

ROOT_DIR=$PWD
CANDIDATE_DIR=$PWD/candidate-release

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cat << EOF > release-repo/config/private.yml
---
blobstore:
  provider: s3
  s3:
    access_key_id: ${BUCKET_ACCESS_KEY}
    secret_access_key: ${BUCKET_SECRET_KEY}
EOF

cd release-repo/

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git merge --no-edit master

RELEASE_YML=$PWD/releases/${RELEASE_NAME}/${RELEASE_NAME}-${VERSION}.yml
RELEASE_TGZ=$PWD/releases/${RELEASE_NAME}/${RELEASE_NAME}-${VERSION}.tgz

if [ -e "${RELEASE_YML}" ]; then
  echo "release already created; making tarball..."
  bosh -n create release --with-tarball "${RELEASE_YML}"
else
  echo "finalizing release"
  bosh -n finalize release --version "$VERSION" ${CANDIDATE_DIR}/${RELEASE_NAME}-*.tgz
  git add -A
  git commit -m "release v${VERSION}"
fi

mv "${RELEASE_TGZ}" "${ROOT_DIR}"
