#!/bin/bash
set -e
set -x

bosh -n target "${BOSH_TARGET}"

set +x
bosh -n login "${BOSH_USERNAME}" "${BOSH_PASSWORD}"
set -x

bosh -n download manifest "${BOSH_DEPLOYMENT}" manifest.yml
bosh -n -d manifest.yml run errand "${BOSH_ERRAND}"
